#!/usr/bin/env python

import sys
import os
from subprocess import call

input = sys.argv[1]
filebase = os.path.basename(input).split(".")[0]
output = filebase + ".html"

call(["rst2html.py", "--stylesheet=rst2html.css", "--cloak-email-addresses", input, output])
