application: likunarmstrong
version: 1
runtime: go
api_version: go1

handlers:
#- url: /icon\.ico
#  static_files: icon.ico
#  upload: icon\.ico
- url: /css
  static_dir: assets/css
- url: /img
  static_dir: assets/img
- url: /js
  static_dir: assets/js
- url: /pdf
  static_dir: assets/pdf
- url: /.*
  script: _go_app
