application: likunarmstrong
version: 1
runtime: go
api_version: go1

#default_expiration: "3d"

handlers:
# SEO
- url: /(robots\.txt|favicon\.ico)
  static_files: web/static/\1
  upload: web/static/(robots\.txt|favicon\.ico)
  #expiration: "10d"

# Fonts
- url: /fonts/(.+\.(eot|otf|tt[cf]|woff2?|cur))
  static_files: web/fonts/\1
  upload: web/fonts/(.+\.(eot|otf|tt[cf]|woff2?|cur))
  http_headers:
    # Allow cross-origin access to web fonts
    # You can also replace "*" with a specific host, e.g. https://example.org
    Access-Control-Allow-Origin: "*"

# Images
- url: /images
  static_dir: web/images
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /css
  static_dir: web/css
  #expiration: "60m"

- url: /js
  static_dir: web/js

- url: /dart
  static_dir: web/dart

- url: /packages
  static_dir: web/dart/packages

- url: /.*
  script: _go_app

skip_files:
  - ^dart$
