version: 1
runtime: go
module: blog
api_version: go1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  max_pending_latency: 50ms
  max_concurrent_requests: 50  # max: 500

default_expiration: "3d"

handlers:
# SEO
- url: /blog/(robots\.txt|favicon\.ico)
  static_files: web/static/\1
  upload: web/static/(robots\.txt|favicon\.ico)

- url: /blog/(.*\.(js))$
  static_files: web/\1
  upload: web/.*\.(js)$

- url: /blog/css
  static_dir: web/css
  #expiration: "60m"

- url: /blog/packages
  static_dir: web/packages

- url: /blog/pdf
  static_dir: static/pdf

- url: /blog/images
  static_dir: static/img

- url: /.*
  script: _go_app

skip_files:
  - ^dart$
  - ^(.*/)?.DS_Store $
  - ^(.*/)?\.rst$
