name: blog
description: A sample Polymer application
dependencies:
    polymer: "any"
    core_elements: "any"
    paper_elements: "any"
transformers:
- polymer:
    entry_points: [web/blog.html, web/post.html]
